### ISSUE TITLE
Algemene werk folder

### ISSUE THREAD

**Issue by cenikk** [RooyyDoe/web-app-from-scratch-1920#1]
Ik zou een algemene folder gebruiken waar al je code in zit en niet wekelijks in een andere folder werken.

**Comment by RooyyDoe** [comment]
Ik gebruik liever week mappen, zodat ik voor mijzelf weet wat ik in een week heb gedaan en op deze manier kan ik ook precies beschrijven hoever ik ben gekomen wanneer dit nodig is per week.
