### ISSUE TITLE
README looks great!

### ISSUE THREAD

**Issue by iamDistractech** [RooyyDoe/web-app-from-scratch-1920#11]
Reading the readme makes me understand what you want to do and how you will do / have done it. 

Had a bit of trouble looking at the actor diagram, but giving it a minute it made more sense. The interaction diagram was simpeler to understand. 

One minor thing: fix the image link in the README  ;) 

Great Job 👍

**Comment by RooyyDoe** [comment]
Fixed the image! thaaankkss 💯
