### ISSUE TITLE
Create some first paint

### ISSUE THREAD

**Issue by iamDistractech** [RooyyDoe/web-app-from-scratch-1920#12]
You could 'render' stuff like the header and other elements before fetching the data(and get some placeholders for the data. When the data is loaded in, you can update the elements with the data. This would make the app feel more asynchronous. 

This is called first paint and gives the user the impression/feedback that the app is loading something.

**Comment by RooyyDoe** [comment]
Made a loading state. So that it gives feedback to the user.
