### ISSUE TITLE
Usage of innerHTML

### ISSUE THREAD

**Issue by iamDistractech** [RooyyDoe/web-app-from-scratch-1920#14]
https://github.com/RooyyDoe/web-app-from-scratch-1920/blob/dff937746473f804c94a63ba909ef07c0cdf3d81/week2/public/modules/createCard.js#L8

You are using `innerHTML` here. Any particular reason?
I haven't worked with handlebars myself, so it could be related to handlebar usage.

Maybe look into alternatives?

**Comment by RooyyDoe** [comment]
Changed it up and created a alternative thanks!
