### ISSUE TITLE
Feedback according to Rubric

### ISSUE THREAD

**Issue by StefanGerrits2** [RooyyDoe/web-app-from-scratch-1920#16]
### App structuur en code kwaliteit:

In `createCard.js` zie ik dat je gebruik maakt van Handlebars, super nice! Maar let even op dat je nog `var` gebruikt in plaats van `let` of `const`.  

Ook goed gebruik al gemaakt van modules. Het komt nog niet helemaal overeen met je actor diagram, maar ik neem aan dat je daar nog mee bezig bent.

Verder ben je wel overal consistent met je code. Ik zou je op dit moment een voldoende geven voor dit punt.

### Data ophalen, manipuleren en tonen:

Ik zie nog geen `map`, `filter`, en `reduce`. Ik neem aan dat je deze later nog gebruikt, zo niet, ga hiermee experimenteren zodat je dit kan laten zien bij de eindbeoordeling.

Je gebruikt Handlebars, volgens mij is dit prima als je dit meerdere keren gebruikt (verschillende pagina's).

Voor nu heb je helaas nog geen voldoende hiervoor.

### States en routes afhandelen

Zover ik zie heb je nog geen router toegevoegd, maar ga je uiteraard wel gebruiken. Een suggestie is bijvoorbeeld de micro librarie `routie.js`.  Deze zie ik al in je repo staan dus je bent er al wel mee bezig!

Interaction diagram ziet er nice uit! Uiteraard heb je nog niet alles uitgewerkt in code, maar als je dit allemaal maakt dan is het super vet en zeker een voldoende waard.

Ook hier nog geen voldoende, maar je heb nog 2 weken dus dat komt vast wel goed :)

Eindscore:

![image](https://user-images.githubusercontent.com/45566396/74520783-8d7fe500-4f18-11ea-9f17-f53b296a5988.png)

**Comment by RooyyDoe** [comment]
Thanks voor de feedback!
