### ISSUE TITLE
Interaction diagram

### ISSUE THREAD

**Issue by StefanGerrits2** [RooyyDoe/web-app-from-scratch-1920#17]
Ziet er nice uit!

Je zou kunnen overwegen om meerdere interaction diagrams te maken in plaats van 1 grote die je nu heb.

Dan maak je dus eigenlijk meerdere makkelijker te begrijpen interaction diagrams.

**Comment by RooyyDoe** [comment]
Ik heb inderdaad mijn interaction diagram opgedeeld in verschillende diagrammen wat het een stuk overzichtelijker maakt! thanks man
