### ISSUE TITLE
README.md Beschrijving

### ISSUE THREAD

**Issue by cenikk** [RooyyDoe/web-app-from-scratch-1920#4]
Ik mis een algemene beschrijving van waar het repo over gaat en wat je in de komende weken gaat doen. [suggestion] Zet ook je leerdoelen hierin, zo kan je aan het einde van dit vak zien of je hieraan bent toegekomen.

**Comment by RooyyDoe** [comment]
Beschrijving heb ik nu toegevoegd thanks! 💯
