### ISSUE TITLE
Code consistency

### ISSUE THREAD

**Issue by StefanGerrits2** [RooyyDoe/web-app-from-scratch-1920#8]
Code consistency is good, but watch the `;` on every line where it could be placed.
For example: Line 12 and 13

https://github.com/RooyyDoe/web-app-from-scratch-1920/blob/7f3e4b44b26fd70fc4765b512dc8c8ca0483b9fc/week1/public/modules/createCard.js#L1-L17

**Comment by RooyyDoe** [comment]
Thanks will do.
