### ISSUE TITLE
Repo feedback

### ISSUE THREAD

**Issue by StefanGerrits2** [RooyyDoe/web-app-from-scratch-1920#9]
* Add a custom description of you web app at the top of your repo.
* You could also start with information about your API
- For example: Fetch limits
   - Do I need a key?
   - Is the API free and open for usage?
   - What kinds of data do you fetch?
   - What is the data structure?

You can implement all this in your readme

**Comment by RooyyDoe** [comment]
- Added a description of my web app. Will be expanded in the future.

**Comment by RooyyDoe** [comment]
- Added a API explaination for my API database
